 "use strict";
 const axios = require ("axios") ;
 //const apikey = "5431486f112421fa932c7bb39b7fc75b"; // your api key to the api generated by the website
 const apikey="1"

 const getRecipe = recipe => {
 return new Promise ( async ( resolve , reject ) => {
 try {
 const recipeApi = await axios .get(

 "https://www.themealdb.com/api/json/v1/1/search.php?s="+`${recipe}`
 ,{params : {key: apikey}}
 ) ;

 resolve ( recipeApi.data ) // returns back the results to the chatbot
 }
 catch ( error ) {
 reject ( error ) ;
 }
 }) ;
 }



 module . exports = getRecipe;
